version: '3.8'

services:
  asiayo-php:
    container_name: asiayo-php
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www/html
    user: www-data:www-data
    networks:
      - asiayo

  asiayo-nginx:
    container_name: asiayo-nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - asiayo-php
      - asiayo-mysql
    networks:
      - asiayo

networks:
  asiayo:
